name: "deploy"
on:
  push:
    paths:
      - ".github/workflows/**"
      - "back/fly.toml"
      - "back/src/**"
      - "back/build.gradle.kts"
      - "back/settings.gradle.kts"
      - "back/Dockerfile"
    branches:
      - "main"
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: back
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
